version: '3.9'

services:
  load_balancer:
    build:
      context: ./loadBalancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      - my_network
    restart: always
    environment:
      - SERVER_IMAGE_NAME=serverimage
      - SERVER_NO = 3

  server:
    build:
      context: ./Server
    image: serverimage
    networks:
      - my_network
    restart: always
    expose:
      - "5000"

networks:
  my_network:
    driver: bridge
