version: "3.9"
services:
  servicename:
    build: ./Server
    image: mainimage
    container_name: maincontainer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      net1:
        aliases:
          - hostnameA
    environment:
      SERVER_ID: 0
networks:
  net1:
